apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  revisionHistoryLimit: 3  # 保持する履歴数を3つに制限
  replicas: 3
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: kick0131/openshift-sample-app:0.0.1
        # コンテナイメージのキャッシュを保持しない
        imagePullPolicy: Always
        #ここを自分のコンテナレジストリのURLに変更します
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-access
              key: SERVICE_DISCOVERY
        - name: DB_PORT  
          valueFrom:
            configMapKeyRef:
              name: mysql-access
              key: PORT_NUMBER
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-access
              key: DB_NAME
