apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE node_app;
    USE node_app;
    CREATE TABLE entries (
        id INT AUTO_INCREMENT PRIMARY KEY,
        content TEXT NOT NULL
    );
    GRANT ALL PRIVILEGES ON node_app.* TO 'user'@'%';
    FLUSH PRIVILEGES;