apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque 
stringData:
  MYSQL_ROOT_PASSWORD: ponyo 
  MYSQL_USER: user
  MYSQL_PASSWORD: password
# 通常のApplication開発において、Secretを公開Repositoryに置くのはNGです。あくまでデモ用途です。