apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: simple-stateful-app
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest/mysql
    repoURL: >-
      https://github.com/kick0131/openshift-simple-stateful-app.git
    #自身のGitlabリポジトリ名に変更します
    targetRevision: main
  project: simple-stateful-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
